### ISSUE TITLE
[Feature request] Option to let browser choose save location before downloading in chromium 

### ISSUE THREAD

**Issue by g-eipi10** [jc3213/download_with_aria2-archived#30]
## Platform
- Operation System: Windows 10 21H2
- Browser: Ungoogled Chromium 96.0.4664.45

## Describe the bug
Sorry I'm not sure if this is a bug or not, but looks like the chromium version doesn't have an option to let browser chooses save location before downloading. In Firefox version I can see it.

## How to reproduce
The steps to reproduce the behavior:
1. Go to extension settings -> Options -> Download -> Choose `Capturing` as `Built-in Filters`. 
2. In Firefox there's an option of `Save Folder: Browser` so I can choose save location on computer from Firefox's built-in before downloading

![image](https://user-images.githubusercontent.com/95273808/144055771-a56ad418-e2b0-414b-a1ba-8191114c5b9e.png)

However, in Chromium, that option doesn't appear, so it just automatically downloads to default folder that I set in aria2

![image](https://user-images.githubusercontent.com/95273808/144055839-db06ff17-1bdd-4b15-b2ae-411f25269c16.png)

I wonder if there's a difference or difficulty in APIs between 2 browsers, and would there be any ways to have this feature? I'm using self-built versions from latest commit (e55f6bc - in both browsers).

Thank you for your great add-on.

**Comment by jc3213** [comment]
It is because the `downloads` API of both browsers work similiar but not exactly the same. This function depends on property `filename` of `downloadItem` object provide by `downloads` API.

Firefox provides full local file path. For example you can get `/user/download/file.extension` on Linux or `C:\downloads\file.extension` on Windows. It's easy to get `dir` option for aria2 request.

Chrome provides only the filename, like `file.extension`. This means you can do nothing further with Chrome.

Sorry, but this is not possible for me to do this work.

**Comment by g-eipi10** [comment]
Ah I see, tks for the info. Actually I was using HTTP Downloader extension before aria2, and I see that they can send download location from chrome to the extension, so I checked the code in `background.js`
[https://github.com/erickutcher/httpdownloader/blob/master/HTTP_Downloader_Chrome_Extension/background.js](https://github.com/erickutcher/httpdownloader/blob/master/HTTP_Downloader_Chrome_Extension/background.js)

I see that they use `onChanged` API from Chrome's `downloads` to get the information of the file going to be saved in computer:
[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/onChanged)

and the `filename` from it can contain the whole path of file going to be saved.

So I mimicked the code from HTTP Downloader and added these to download_with_aria2's `background.js` file

```js
function OnDownloadItemChange(item) {
    console.log(item.filename);
}
chrome.downloads.onChanged.addListener( OnDownloadItemChange );
```

And after inspecting the console of the background page, I see it can really see the whole path of the file

![image](https://user-images.githubusercontent.com/95273808/144219643-b376ffe8-3a03-4da9-a92f-1f0fd4f0989e.png)

However, HTTP Downloader extension uses some ways to interrupt the download. I'm not sure how exactly download_with_aria2 interrupts and transfers the download so I don't know if this can be implemented or not. I'm not good at javascript and HTML so it might take a long time for me to implement myself and make a pull request, and this is the best I can do now, sorry about that.

**Comment by jc3213** [comment]
OK, this may be tricky to do it, I can have a try though

**Comment by jc3213** [comment]
I've make a patch for `background.js`, This is tricky and I don't want to merge it into the main branch. You also need `/options/index.html` from Firefox to make it work.

If you've already using the extension before the patch, you may have problem when open `options` page for changing options.
You can run these codes in `background page` to fix the issue.
```javascript
aria2RPC.folder.mode = '0'
aria2RPC.folder.uri = ''
chrome.storage.local.set(aria2RPC)
```

Here's the patch
```javascript
chrome.downloads.onChanged.addListener(item => this.path = item.filename.current);

chrome.downloads.onDeterminingFilename.addListener(item => {
    if (aria2RPC.capture['mode'] === '0' || item.finalUrl.startsWith('blob') || item.finalUrl.startsWith('data')) {
        return;
    }

    chrome.tabs.query({active: true, currentWindow: true}, tabs => {
        var url = item.finalUrl;
        var referer = item.referrer && item.referrer !== 'about:blank' ? item.referrer : tabs[0].url;
        var domain = getDomainFromUrl(referer);
        var filename = item.filename;

        if (captureDownload(domain, getFileExtension(filename), item.fileSize)) {
            chrome.downloads.cancel(item.id, () => {
                chrome.downloads.erase({id: item.id}, () => {
                    startDownload({url, referer, domain, filename, folder: aria2RPC.folder['mode'] === '1' ? this.path.slice(0, this.path.indexOf(filename)) : aria2RPC.folder['mode'] === '2' ? aria2RPC.folder['uri'] : null});
                });
            });
        }
    });
});

function startDownload({url, referer, domain, filename, folder}, options = {}) {
    chrome.cookies.getAll({url}, cookies => {
        options['header'] = ['Cookie:', 'Referer: ' + referer, 'User-Agent: ' + aria2RPC['useragent']];
        cookies.forEach(cookie => options['header'][0] += ' ' + cookie.name + '=' + cookie.value + ';');
        if (folder) {
            options['dir'] = folder;
        }
        if (filename) {
            options['out'] = filename;
        }
        if (aria2RPC.proxy['resolve'].includes(domain)) {
            options['all-proxy'] = aria2RPC.proxy['uri'];
        }
        downloadWithAria2(url, options);
    });
}
```

**Comment by g-eipi10** [comment]
Tks a lot for the patch. However, I'm not sure if I've added correctly. I used `index.html` file from firefox, changed the options `Capturing` to `Built-in Filters` and `Save Folder` to `Browser`, and tested a download. In the `background page` console, it occurs this error:
`Error in event handler: TypeError: Cannot read properties of undefined (reading 'current')`

![image](https://user-images.githubusercontent.com/95273808/144238965-bc69646e-9a29-4a50-a5e8-0e5bb4b839a7.png)

which is from the line

```js
chrome.downloads.onChanged.addListener(item => this.path = item.filename.current);
```

![image](https://user-images.githubusercontent.com/95273808/144239087-385ae888-7f9a-42de-9250-fc79f1aeb102.png)

**Comment by jc3213** [comment]
It works for me though, I think it is because the code `cancel` the download first then `remove` it, `onChanged` event has been triggered twice and the last time, there's no `filename` property for `downloadItem`

I'll try to fix then patch it here https://github.com/jc3213/download_with_aria2-archived/issues/30#issuecomment-983589054

**Comment by jc3213** [comment]
I've done more tests, This patch only works for `Default Download Folder` on Chrome. If you try to use `Save As` when download prompt popup, there will be an error, cause no `downloadItem.filename` is defined.

This patch works for `Save` or `Open` only, and is not ready for common usage.
![1](https://user-images.githubusercontent.com/8744936/144346777-4181ff8f-22af-4f9f-8eaa-b19160d349f8.png)

**Comment by g-eipi10** [comment]
Yup, I was about to report the same behavior. I will try to see how to overcome this.

**Comment by g-eipi10** [comment]
I guess the reason it failed is that the download canceling and starting should be in the `onChanged` event. So I tested with declaring a global variable to store the download information and split the `onDeterminingFilename` event to 2 parts: first part is to get the download information and the second part (download part) is inside `onChanged` event.

<details><summary>background.js</summary>

```js
var disabled = false;
var download_info = new Object()
download_info = {};

chrome.contextMenus.create({
    title: chrome.i18n.getMessage('extension_name'),
    id: 'downwitharia2',
    contexts: ['link']
});

chrome.contextMenus.onClicked.addListener(info => {
    if (info.menuItemId === 'downwitharia2') {
        startDownload({url: info.linkUrl, referer: info.pageUrl, domain: getDomainFromUrl(info.pageUrl)});
    }
});

chrome.browserAction.setBadgeBackgroundColor({color: '#3cc'});

chrome.downloads.onDeterminingFilename.addListener(item => {
    if (aria2RPC.capture['mode'] === '0' || item.finalUrl.startsWith('blob') || item.finalUrl.startsWith('data')) {
        disabled = true;
        return;
    }

    chrome.tabs.query({active: true, currentWindow: true}, tabs => {
        download_info.url = item.finalUrl;
        download_info.referer = item.referrer && item.referrer !== 'about:blank' ? item.referrer : tabs[0].url;
        download_info.domain = getDomainFromUrl(download_info.referer);
        download_info.filename = item.filename;
        download_info.fileSize = item.fileSize;
    });
});

chrome.downloads.onChanged.addListener(item => {
    if (disabled === true){
        return;
    }
    if (item.filename) {
        if (item.filename.current != '') {
            download_info.path = item.filename.current;
        }
        else {
            download_info.path = '';
        }
        var url = download_info.url;
        var referer = download_info.referer;
        var domain = download_info.domain;
        var filename = download_info.filename;
        if (captureDownload(domain, getFileExtension(filename), download_info.fileSize)) {
            chrome.downloads.cancel(item.id, () => {
                var folder = aria2RPC.folder['mode'] === '1' ? download_info.path.slice(0, download_info.path.indexOf(filename)) : aria2RPC.folder['mode'] === '2' ? aria2RPC.folder['uri'] : null;
                chrome.downloads.erase({id: item.id}, () => {
                    startDownload({url, referer, domain, filename, folder});
                });
            });
        }
    }
});

function startDownload({url, referer, domain, filename, folder}, options = {}) {
    chrome.cookies.getAll({url}, cookies => {
        options['header'] = ['Cookie:', 'Referer: ' + referer, 'User-Agent: ' + aria2RPC['useragent']];
        cookies.forEach(cookie => options['header'][0] += ' ' + cookie.name + '=' + cookie.value + ';');
        if (folder != '') {
            options['dir'] = folder;
        }
        if (filename) {
            options['out'] = filename;
        }
        if (aria2RPC.proxy['resolve'].includes(domain)) {
            options['all-proxy'] = aria2RPC.proxy['uri'];
        }
        downloadWithAria2(url, options);
    });
}

function captureDownload(domain, fileExt, fileSize) {    
    if (aria2RPC.capture['reject'].includes(domain)) {
        return false;
    }
    if (aria2RPC.capture['mode'] === '2' || aria2RPC.capture['mode'] === '1') {
        return true;
    }
    if (aria2RPC.capture['resolve'].includes(domain)) {
        return true;
    }
    if (aria2RPC.capture['fileExt'].includes(fileExt)) {
        return true;
    }
    if (aria2RPC.capture['fileSize'] > 0 && fileSize >= aria2RPC.capture['fileSize']) {
        return true;
    }
    return false;
}

function getDomainFromUrl(url) {
    var host = /^https?:\/\/([^\/]+)\//.exec(url)[1];
    var hostname = /:\d{2,5}$/.test(host) ? host.slice(0, host.lastIndexOf(':')) : host;
    if (hostname.includes(':')) {
        return hostname.slice(1, -1);
    }
    if (/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$|^[^\.]+\.[^\.]+$/.test(hostname)) {
        return hostname;
    }
    var suffix = /([^\.]+)\.([^\.]+)\.([^\.]+)$/.exec(hostname);
    var gSLD = ['com', 'net', 'org', 'edu', 'gov', 'co', 'ne', 'or', 'me'];
    return gSLD.includes(suffix[2]) ? suffix[1] + '.' + suffix[2] + '.' + suffix[3] : suffix[2] + '.' + suffix[3];
}

function getFileExtension(filename) {
    return filename.slice(filename.lastIndexOf('.') + 1).toLowerCase();
}

function aria2RPCClient() {
    aria2RPCRequest({id: '', jsonrpc: 2, method: 'aria2.getGlobalStat', params: [aria2RPC.jsonrpc['token']]},
    global => chrome.browserAction.setBadgeText({text: global.numActive === '0' ? '' : global.numActive}),
    error => {
        if (aria2Error === 0) {
            aria2Error = showNotification(error) ?? 1;
        }
    }, true);
}
```

</details>

It works for me, but it looks not really nice and I have to split your code, which I tried to avoid but failed. Also there are 2 downsides that I don't know how to fix:

- In the line

```js
if (aria2RPC.capture['mode'] === '2' || aria2RPC.capture['mode'] === '1') {
    return true;
}
```

I have to add `aria2RPC.capture['mode'] === '1'` if I want to use `Built-in Filters`. I don't know why in Firefox it doesn't need that but still works.

- When installing the extension, I have to follow these exact steps: run your 2 lines in `background page` and choose `Capturing, Built-in Filters/Always` right after that, to make it work. If I forget any of these steps, it will not work as expected. I'm not sure how to fix this.

**Comment by jc3213** [comment]
You should keep `/options.json` from Firefox if you need the `Save Folder` function, since there's no options for it by default and will cause error.

If you do fix your problem, it will be OK.

They are the same meaning, once one of them should be OK
```javascript
var download_info = new Object()
download_info = {};
```

In your code, once `disabled` is set to `true`, you have no code to set it back to `false`, there will be problem, if `capture.mode` have been changed to `0`

**Comment by g-eipi10** [comment]
Oh I see, tks for your advice. I'll fix those and check if it works.

**Comment by g-eipi10** [comment]
Yup, I confirm that changing `options.json` to be similar to Firefox's makes it work perfect now :+1:

**Comment by jc3213** [comment]
Here's my code. I wonder if I can use `onChanged` event for Firefox to solve the `fileSize` problem, as Mozilla devs mentioned it. I'll see if it will do the magic. Once it is working, I'll merge all changes to `main` branch`

[background.zip](https://github.com/jc3213/download_with_aria2-archived/files/7639362/background.zip)

**Comment by jc3213** [comment]
I've tried on Firefox, `onChanged` event is just a piece of shit.
![1](https://user-images.githubusercontent.com/8744936/144368837-7feb4aed-0466-4bc1-ba1f-bf4c6c75cc3f.png)
![2](https://user-images.githubusercontent.com/8744936/144368728-57d42e2e-1b2e-4d0c-85a8-aafa070ae4ca.png)

**Comment by g-eipi10** [comment]
> Here's my code. I wonder if I can use `onChanged` event for Firefox to solve the `fileSize` problem, as Mozilla devs mentioned it. I'll see if it will do the magic. Once it is working, I'll merge all changes to `main` branch`
> 
> [background.zip](https://github.com/jc3213/download_with_aria2-archived/files/7639362/background.zip)

Oh tks for your cleaner code. There are 2 issues when I tested with it:

- When I select `Built-in Filters` + `Save Folder: Browser`, it cannot catch the download and the browser just downloads the file itself. When I changed this line (add capture mode 1) as in my previous problem, it catches normally now

```js
if (aria2RPC.capture['mode'] === '2' || aria2RPC.capture['mode'] === '1') {
    return true;
}
```
- I think the `startDownload` function lacks `folder` parameter and an `options['dir']` so when I downloaded the file, it just goes to the `aria2c.exe` folder. So I changed the code to your previous suggest

```js
function startDownload({url, referer, domain, filename, folder}, options = {}) {
    chrome.cookies.getAll({url}, cookies => {
        options['header'] = ['Cookie:', 'Referer: ' + referer, 'User-Agent: ' + aria2RPC['useragent']];
        cookies.forEach(cookie => options['header'][0] += ' ' + cookie.name + '=' + cookie.value + ';');
        if (folder != '') {
            options['dir'] = folder;
        }
        if (filename) {
            options['out'] = filename;
        }
        if (aria2RPC.proxy['resolve'].includes(domain)) {
            options['all-proxy'] = aria2RPC.proxy['uri'];
        }
        downloadWithAria2(url, options);
    });
}
```

// And yeah, I saw your comments in Firefox code about the `filesize`. Looks like it's really hard to solve if it's a bug from Mozilla.

**Comment by g-eipi10** [comment]
I just checked with Edge, and looks like for chromium browsers that have another operation between pressing downloading and choosing saving location (for example in Edge it has a popup of choosing `Open` or `Save As` before really go to the choosing location step), it's hard to make the extension to know and wait for `Save As` function. It will send the download information right after clicking download.
